### ISSUE TITLE
fast function for checking the existence of an edge?

### ISSUE THREAD

**Issue by edward-kao** [rohitvarkey/StingerGraphs.jl#39]
Is there a fast function for checking if an edge exist, given the src and dest? I suppose I can just use edgeweight to see if it returns 0, but perhaps there is a faster way? Thank you!

**Comment by jpfairbanks** [comment]
If you are trying to check for a single edge, the edgeweight function is pretty close to the best you can do. If you can batch up the checks so that you are checking for many vertices for a single source vertex, then you can do better.

There is some C/Julia call overhead that can be reduced, but I am not sure how much faster it would be.

**Comment by rohitvarkey** [comment]
I agree with @jpfairbanks on this. Due to the way STINGER stores edges, we will need to iterate through the edgeblocks to figure out if the edge exists or not.
